Repository PEC-CSS/graveyard, pull requests merged in 2023-03, with the labels that each got.

#49 Averaging Fibonacci Series
  dsa/AveragingFibonacciSeries.py
Labels: pwoc, graveyard

#51 Basic Recursion Problem
  dsa/Basic Recurssion problem.cpp
  ml/Create a 4x3 integer array.py
Labels: pwoc, graveyard

#40 Create a 4x3 integer array
  dsa/Basic Recurssion problem.cpp
  ml/Create a 4x3 integer array.py
Labels: pwoc, graveyard

#47 Delete a column in 2D array
  ml/Delete a column in 2D matrix.py
Labels: pwoc, graveyard

#48 issue 13
  dsa/merge 2 sorted lists.py
Labels: pwoc, graveyard

#44 Replace even numbers in array with mean of elements
  dsa/graph.cpp
  dsa/graph.exe
  ml/replace_even_num.py
Labels: pwoc, graveyard

#55 Resolved issue #12
  dsa/graph.cpp
  dsa/graph.exe
  ml/replace_even_num.py
Labels: pwoc, graveyard

#50 Web
  issue26.html
Labels: pwoc, graveyard

#80 Issue24 Replicating Image (added to web folder)
  web/issue24.html
  web/issue26.html
Labels: pwoc, graveyard

#79 Dice roll using js and html
  web/dice roll.html
Labels: pwoc, graveyard

#81 Mean Along Each Column
  ml/Mean Along Each Column.py
Labels: pwoc, graveyard

#91 Issue#11DSA arrange stack in decreasing order
  dsa/issue#11.py
  web/issue24.html
Labels: pwoc, graveyard

#92 minimum add to make a parentheses valid
  dsa/minimum add to make a parentheses valid.java
Labels: DSA, pwoc, graveyard

#102 Resolved Issue27 Replicating the Image
  web/issue27.html
Labels: pwoc, graveyard

#103 Issue#56 creating dataframes from dictionary
  ml/issue#56.py
Labels: ML, pwoc, graveyard

#99 Tour of King
  cp/TourofKing.py
Labels: CP, pwoc, graveyard

#98 Creating an Array containing the squares of another array in a non decreasing order #10
  dsa/array_sqaured.py
Labels: DSA, pwoc, graveyard

#39 Check If N and Its Double Exist #20
  misc/N and its Double.c
Labels: pwoc, graveyard

#105 Minimum Absolute Difference
  dsa/MinAbsDiff.py
Labels: pwoc, graveyard

#104 #83, dsa, solved, leetcode accepttance ss attached
  dsa/shortest-dist.py
Labels: pwoc, graveyard

#100 Find the divisibility array of a string
  dsa/Find the divisibility array of a string.py
Labels: pwoc, graveyard

#115 Python pokeapi call #109
  misc/pikachu.py
Labels: pwoc, graveyard

#117 Issue #4 finding common elements n concatenating two np arrays
  ml/issue4.py
Labels: pwoc, graveyard

#112 Class implementing complex numbers #110
  misc/complex.py
Labels: pwoc, easy

#116 Capacity to ship packages within D days. #88
  dsa/capacity to ship packages within D days.java
Labels: pwoc, graveyard

#118 Replaced dataframe #106
  ml/dataframe-replace.ipynb
Labels: ML, pwoc, graveyard

#113 Filtered dataframe #107
  ml/filtered_dataframe.ipynb
Labels: pwoc, graveyard

#119 End of plots #69
  ml/data-plots.ipynb
Labels: pwoc, graveyard

#121 Find in Mountain Array
  dsa/MountainArray.java
Labels: pwoc, graveyard

#125 Temperature Convertor JS
  web/tempConvertor/index.js
  web/tempConvertor/package.json
Labels: pwoc, graveyard

#123 Two sum #23
  dsa/two sum.py
Labels: DSA, pwoc, graveyard

#124 Convert Sorted Array to Binary Search Tree
  dsa/convertSortedArrayToBinarySearchTree.cpp
Labels: pwoc, graveyard

#42 DSA || GAS STATION(GREEDY)
  dsa/DSA || GAS STATION(GREEDY) #33.py
Labels: pwoc, graveyard

#127 Write JS code for greeting users #28
  web/greeting.js
Labels: pwoc, graveyard

#74 Reloved issue #54
  dsa/graph.exe
  ml/return_count.py
Labels: pwoc, graveyard

#129 Series of capital cities
  ml/Series of capital cities #60.ipynb
Labels: pwoc, graveyard

#126 Sort odd number in a numpy array #1
  ml/Sort odd number in a numpy array #1.ipynb
Labels: pwoc, graveyard

#140 Issue135 Consecutive Integers in an array
  cp/issue135.py
Labels: pwoc, graveyard

#141 Completed Issue - Create matrix and access rows and columns
  ml/Create_matrix_access_rows_columns.py
Labels: ML, pwoc, graveyard

#137 City dataframe #61
  ml/city-dataframe.ipynb
Labels: pwoc, graveyard

#152 Resolved Issue #144 Taking input from command line in Python
  misc/takeInputFromTerminal.py
Labels: pwoc, graveyard

#159 remove_duplicates
  dsa/remove_duplicates.py
Labels: pwoc, graveyard

#166 Issue25
  web/issue25.html
Labels: pwoc, graveyard

#120 resolved issue Numbers between a given range
  ml/Numbers between a given range .py
Labels: pwoc, graveyard

#174 Issue #156
  cp/issue156.cpp
Labels: pwoc, graveyard

#153 Taking input from command line in Java #147
  misc/cmdinput.java
Labels: pwoc, graveyard

#177 gas station # 66
  dsa/gas station.py
  dsa/ifstringsaresorted.cpp
Labels: pwoc, graveyard

#183 API Call Using Javascript
  web/APIcallUsingJavaScript.js
Labels: Web, pwoc, graveyard

#101 Given 2 numpy arrays return unique elements
  ml/Given 2 numpy arrays return unique elements.py
Labels: ML, pwoc, graveyard

#186 Writing into file instead of directly printing
  misc/Writing into file instead of directly printing.py
Labels: pwoc, graveyard

#167 Carl's Training #157
  cp/Polycarp.java
Labels: pwoc, graveyard

#173 Write a command line application in language of your choice for a TODO app
  misc/Write a command line application in language of your choice for a TODO app.py
Labels: pwoc, graveyard

#169 Resolve Issue - Find Percentile
  ml/Find_Percentile.py
Labels: pwoc, graveyard

#191 Resolved issue 146 Creating Iframes
  web/issue146.html
Labels: pwoc, graveyard

#198 Resolved Issue 138 BMI Calculator
  web/issue138.html
Labels: pwoc, graveyard

#193 Ageing
  cp/ageing.cpp
Labels: pwoc, graveyard

#209 Resolved Issue 203 Handling Missing Values
  ml/issue203/Untitled-1.ipynb
  ml/issue203/data1.xlsx
Labels: pwoc, graveyard

#211 BooleanIndexing #196
  ml/BooleanIndexing.py
Labels: pwoc, graveyard

#187 Longest substring
  cp/longest substring.py
Labels: pwoc, graveyard

#139 Largest number #136
  cp/largest-number.py
Labels: pwoc, graveyard

#181 chocochallenge #15
  cp/chocochallenge.cpp
Labels: pwoc, graveyard

#218 Simple Linear Regression
  ml/Simple Linear Regression.py
Labels: pwoc, graveyard

#224 Categorical Data
  ml/categoricalData.ipynb
  ml/titanic.csv
Labels: pwoc, graveyard

#229 Issue204 hamburger menu resolved
  web/hamburger menu/index.html
  web/hamburger menu/script.js
  web/hamburger menu/style.css
Labels: pwoc, graveyard

#228 Stopwatch
  web/stopWatch.html
  web/stopWatch.js
Labels: pwoc, graveyard

#231 North Indian Cuisine #200
  ml/north-indian-cuisine.ipynb
Labels: pwoc, graveyard

#210 Create a quiz using simple HTML and JS
  web/Create a quiz using simple HTML and JS.html
Labels: pwoc, easy

#233 Resolved Issue 133 creating console application
  misc/issue134.java
Labels: pwoc, graveyard

#192 XOR IT UP
  cp/XOR IT Up.py
Labels: pwoc, graveyard

#225 EmbeddingVectors #197
  ml/EmbeddingVectors.py
Labels: pwoc, graveyard

#234 Can he play #232
  cp/can-play.py
Labels: pwoc, graveyard

#226 Print all codes (Issue #206)
  cp/print all codes.py
Labels: pwoc, graveyard

#235 Save Energy
  cp/minimum energy.cpp
Labels: pwoc, graveyard

#175 IPL Teams #162
  IPLteams.html
Labels: pwoc, graveyard

#170 Find X
  .vscode/settings.json
  cp/FindX.java
Labels: pwoc, graveyard
